old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            # requires sockets extension
            use_socket: true # default false
    producers:
        calc_salaries:
            connection:       default
            exchange_options: {name: 'calc_salaries', type: direct}
            service_alias:    'App\Producer\CalcSalariesProducer'
    consumers:
        calc_salaries:
            connection:       default
            exchange_options: {name: 'calc_salaries', type: direct}
            queue_options:    {name: 'calc_salaries'}
            callback:         'App\Consumer\CalcSalariesConsumer'
