# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Replacing JMS Serializer's object constructor with the doctrine_object_constructor
    # results in merging the deserialized fields with the Doctrine entity (which is optionally
    # fetched from database)
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    App\Service\Calculator\SalaryCalculatorInterface: '@App\Service\Calculator\SalaryCalculator'

    App\Producer\EventProducer:
        class: 'App\Producer\EventProducer'
        arguments:
            - '@old_sound_rabbit_mq.connection.default'
            - calc_salaries
            - calc_salaries

    App\Producer\EventProducerInterface: '@App\Producer\EventProducer'

    App\Consumer\CalcSalariesConsumer:
        class: 'App\Consumer\CalcSalariesConsumer'
        arguments:
            - '@doctrine.orm.entity_manager'
        public: true

    sonata.admin.employee:
        class: App\Admin\EmployeeAdmin
        arguments: [~, App\Entity\Employee, ~]
        calls:
            - [setSalaryCalculator, ['@App\Service\Calculator\SalaryCalculatorInterface']]
            - [setSalaryFactorRepository, ['@App\Repository\SalaryFactorRepository']]
            - [setEventProducer, ['@App\Producer\EventProducerInterface']]
            - [setLogger, ['@logger']]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: "Employees"
              group: "People"
              icon: '<i class="fa fa-users"></i>'

    sonata.admin.salary_factor:
        class: App\Admin\SalaryFactorAdmin
        arguments: [~, App\Entity\SalaryFactor, ~]
        calls:
            - [setTemplate, ['edit', 'Admin/SalaryFactorAdmin/edit.html.twig']]
            - [setLogger, ['@logger']]
            - [setEmployeeRepository, ['@App\Repository\EmployeeRepository']]
            - [setEventProducer, ['@App\Producer\EventProducerInterface']]
        tags:
            - name: sonata.admin
              manager_type: orm
              label: 'Salary Factors'
              icon: '<i class="fa fa-gear"></i>'
              group: 'Settings'
