<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20191003130244 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Creates salary_factor table';
    }

    public function up(Schema $schema) : void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql(
            'CREATE TABLE salary_factor (
                id INT AUTO_INCREMENT NOT NULL,
                `name` VARCHAR(255) NOT NULL DEFAULT "N/A/",
                `rules` LONGTEXT NOT NULL COMMENT "JSON generated by QueryBuilder on the front end",
                `type` INT NOT NULL DEFAULT 1 COMMENT "The type of salary factor. 1 - bonus, 2 - deduction",
                `value` DOUBLE PRECISION NOT NULL DEFAULT 0 COMMENT "The value to be added/deduced to/from the base salary",
                value_type INT NOT NULL DEFAULT 1 COMMENT "The type of the value field. 1 - number, 2 - percents",
                `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
                modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
                PRIMARY KEY(id),
                INDEX `name`(`name`(24)),
                INDEX `type`(`type`),
                INDEX `value_type`(`value_type`)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB COMMENT "Factors affecting employee actual salary"');
    }

    public function down(Schema $schema) : void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE salary_factor');
    }
}
